name: 1.1.0$(Rev:.r) #Build number

pr: none

resources:
  pipelines:
    - pipeline: Common
      source: Common
      trigger:
        branches:
        - dev
       
trigger:
  batch: "true"
  branches:
    include:
    - dev
  paths:
    include:
    - Apps/Immunization

jobs:
- job: OpenShift 3 - Build and Package
  pool:
    name: "HealthGateway"
  extends:
    template: /Build/hg.yaml
    parameters:
      Application: Immunization
      DotNetTests: true
      FunctionalTests: false
      NPMInstall: false
      NPMTests: false

- job: OpenShift 4 - Build and Package
  pool:
    name: "HealthGatewayOCP4"
  steps:
  - script: |
        set -e
        oc projects
    displayName: "Test" 

