name: 1.1.0$(Rev:.r) #Build number

pr:
    branches:
        include:
        - dev
    paths:
        include:
        - Apps/Immunization     # Should be set to App.Name
        - Apps/Common
        - Apps/Database

trigger:
    batch: "true"
    branches:
        include:
        - dev
    paths:
        include:
        - Apps/Immunization     # Should be set to App.Name
        - Apps/Common
        - Apps/Database

extends:
  template: /Build/hg.yaml
  parameters:
    Application: Immunization
    UnitTests: true
    FunctionalTests: false
