apiVersion: v1
kind: Template
metadata:
  name: ${NAME}-template
  labels:
    app: ${NAME}
objects:
  - apiVersion: v1
    stringData:
      HealthGateway_AcaPy__agentApiUrl: ${AGENT_URL}
      HealthGateway_AcaPy__agentApiKey: ${AGENT_KEY}
      HealthGateway_AcaPy__webhookApiKey: ${WEBHOOK_KEY}
    kind: Secret
    metadata:
      name: ${NAME}-secrets
      labels:
        app: ${NAME}
    type: Opaque

parameters:
  - name: NAME
    displayName: Template Name
    description: The name of the template and all related entities (override for multiple deployments in the same namespace)
    value: acapy
    required: true
  - name: AGENT_URL
    displayName: The Agent URL
    description: The Aca-Py agent URL to use for the environment
    required: true
  - name: AGENT_KEY
    displayName: The Agent API Key
    description: The API Key that the Aca-Py agent uses to authorize access from WebClient
    required: true
  - name: WEBHOOK_KEY
    displayName: The WebClient API Key
    description: The API Key that WebClient uses to authoize access from the Aca-Py agent
    required: true
